version: "3.9"

services:
  grpc-service1:
    &grpc_service1
    container_name: grpc_backend_1
    build:
      context: ..
      dockerfile: Dockerfile
    volumes:
      - ../.bin/:/root/
    env_file:
      - ../.env
    environment:
      - GRPC_PORT=9009
    depends_on:
      - grpc-db
    restart: on-failure
  grpc-service2:
    <<: *grpc_service1
    container_name: grpc_backend_2
    environment:
      - GRPC_PORT=9008
  grpc-nginx:
    container_name: grpc_nginx
    image: nginx:1.21.6-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - nginx_logs:/etc/nginx/logs
    ports:
      - "80:80"
  grpc-db:
    container_name: grpc_db
    image: mongo:4.4-bionic
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=g0langn1nja
    restart: on-failure
volumes:
  mongo_data:
  nginx_logs: